### ISSUE TITLE
expected search result doesn't appear

### ISSUE THREAD

**Issue by theyelllowdart** [theyelllowdart/consensus#1]
plerumque

http://api.soundcloud.com/tracks?client_id=bea3e36a337bd563d7ea12b7f6e20861&limit=20&q=plerumque

**Comment by theyelllowdart** [comment]
The second item in the results list is null which crashed the controller. I'll add a guard.
![screen shot 2015-06-08 at 9 21 17 pm](https://cloud.githubusercontent.com/assets/1833894/8048827/5c32b750-0e24-11e5-832e-8ed3a4c59d13.png)

**Comment by parkan** [comment]
oh soundcloud :(
